services:
  sqlalchemy_models:
    build: .
    container_name: sqlalchemy_models
    env_file: .env
    tty: true
    entrypoint: bash
    volumes:
      - .:/sqlalchemy_models
  db:
    image: postgres:15.5
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: development
